// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_223_RECOMP_H
#define _DLL_223_RECOMP_H

#define cannon_claw_dtor __dll223_cannon_claw_dtor
#define cannon_claw_func_18 __dll223_cannon_claw_func_18
#define cannon_claw_ctor __dll223_cannon_claw_ctor
#define cannon_claw_func_1B4 __dll223_cannon_claw_func_1B4
#define cannon_claw_func_200 __dll223_cannon_claw_func_200
#define cannon_claw_func_28C __dll223_cannon_claw_func_28C
#define cannon_claw_func_27C __dll223_cannon_claw_func_27C
#define cannon_claw_func_4C __dll223_cannon_claw_func_4C
#define cannon_claw_func_20C __dll223_cannon_claw_func_20C
#define cannon_claw_func_26C __dll223_cannon_claw_func_26C

#endif //_DLL_223_RECOMP_H
