// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_270_RECOMP_H
#define _DLL_270_RECOMP_H

#define dll_270_func_48 __dll270_dll_270_func_48
#define dll_270_dtor __dll270_dll_270_dtor
#define dll_270_func_8C __dll270_dll_270_func_8C
#define dll_270_func_6C __dll270_dll_270_func_6C
#define dll_270_func_3C __dll270_dll_270_func_3C
#define dll_270_ctor __dll270_dll_270_ctor
#define dll_270_func_18 __dll270_dll_270_func_18
#define dll_270_func_54 __dll270_dll_270_func_54
#define dll_270_func_7C __dll270_dll_270_func_7C

#endif //_DLL_270_RECOMP_H
