// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_296_RECOMP_H
#define _DLL_296_RECOMP_H

#define _data_0 __dll296__data_0
#define _data_4 __dll296__data_4
#define _data_8 __dll296__data_8
#define _data_20 __dll296__data_20
#define _data_2C __dll296__data_2C
#define _data_34 __dll296__data_34
#define _data_40 __dll296__data_40
#define dll_296_func_C50 __dll296_dll_296_func_C50
#define _rodata_0 __dll296__rodata_0
#define _rodata_4 __dll296__rodata_4
#define _rodata_8 __dll296__rodata_8
#define _rodata_C __dll296__rodata_C
#define _rodata_10 __dll296__rodata_10
#define dll_296_func_9C0 __dll296_dll_296_func_9C0
#define dll_296_draw __dll296_dll_296_draw
#define dll_296_destroy __dll296_dll_296_destroy
#define dll_296_get_state_size __dll296_dll_296_get_state_size
#define dll_296_update __dll296_dll_296_update
#define dll_296_create __dll296_dll_296_create
#define dll_296_dtor __dll296_dll_296_dtor
#define dll_296_ctor __dll296_dll_296_ctor
#define dll_296_func_C2C __dll296_dll_296_func_C2C

#endif //_DLL_296_RECOMP_H
