// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_365_RECOMP_H
#define _DLL_365_RECOMP_H

#define func_0006 __dll365_func_0006
#define func_0005 __dll365_func_0005
#define func_0001 __dll365_func_0001
#define fini __dll365_fini
#define func_0004 __dll365_func_0004
#define func_0003 __dll365_func_0003
#define init __dll365_init
#define func_0002 __dll365_func_0002
#define func_0007 __dll365_func_0007
#define func_0000 __dll365_func_0000

#endif //_DLL_365_RECOMP_H
