// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_20_RECOMP_H
#define _DLL_20_RECOMP_H

#define sLoadedScreenByteLength __dll20_sLoadedScreenByteLength
#define screens_ctor __dll20_screens_ctor
#define sLoadedScreenNo __dll20_sLoadedScreenNo
#define screens_show_screen __dll20_screens_show_screen
#define sRenderScreen __dll20_sRenderScreen
#define screens_hide_screen __dll20_screens_hide_screen
#define sLoadedScreen __dll20_sLoadedScreen
#define screens_draw __dll20_screens_draw
#define screens_dtor __dll20_screens_dtor

#endif //_DLL_20_RECOMP_H
