// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_28_RECOMP_H
#define _DLL_28_RECOMP_H

#define sFadeAlpha __dll28_sFadeAlpha
#define sFadeSpeed __dll28_sFadeSpeed
#define sAutoReverseTimer __dll28_sAutoReverseTimer
#define sFadeType __dll28_sFadeType
#define sIsComplete __dll28_sIsComplete
#define sDelayTimer __dll28_sDelayTimer
#define screen_fade_draw_simple_black __dll28_screen_fade_draw_simple_black
#define screen_fade_draw_simple __dll28_screen_fade_draw_simple
#define screen_fade_draw_radial __dll28_screen_fade_draw_radial
#define screen_fade_fade_reversed __dll28_screen_fade_fade_reversed
#define screen_fade_func_3AC __dll28_screen_fade_func_3AC
#define screen_fade_dtor __dll28_screen_fade_dtor
#define screen_fade_fade __dll28_screen_fade_fade
#define screen_fade_draw __dll28_screen_fade_draw
#define screen_fade_get_progress __dll28_screen_fade_get_progress
#define screen_fade_ctor __dll28_screen_fade_ctor
#define screen_fade_is_complete __dll28_screen_fade_is_complete

#endif //_DLL_28_RECOMP_H
