// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_30_RECOMP_H
#define _DLL_30_RECOMP_H

#define task_get_num_recently_completed __dll30_task_get_num_recently_completed
#define sRecentlyCompleted __dll30_sRecentlyCompleted
#define task_mark_task_completed __dll30_task_mark_task_completed
#define task_ctor __dll30_task_ctor
#define task_get_completion_percentage __dll30_task_get_completion_percentage
#define task_get_completion_task_text __dll30_task_get_completion_task_text
#define task_dtor __dll30_task_dtor
#define task_load_recently_completed __dll30_task_load_recently_completed
#define sCompletionIdx __dll30_sCompletionIdx
#define task_get_recently_completed_task_text __dll30_task_get_recently_completed_task_text
#define sRecentlyCompletedNextIdx __dll30_sRecentlyCompletedNextIdx

#endif //_DLL_30_RECOMP_H
