// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_31_RECOMP_H
#define _DLL_31_RECOMP_H

#define sFlashDmaMqBuffer __dll31_sFlashDmaMqBuffer
#define sFlashDmaMq __dll31_sFlashDmaMq
#define sFlashIoMesg __dll31_sFlashIoMesg
#define sFlashId __dll31_sFlashId
#define sFlashReadIoMesg __dll31_sFlashReadIoMesg
#define sFlashReadIdQueue __dll31_sFlashReadIdQueue
#define sFlashEPiHandle __dll31_sFlashEPiHandle
#define sFlashReadIdQueueBuffer __dll31_sFlashReadIdQueueBuffer
#define DAT_81084030 __dll31_DAT_81084030
#define flash_compute_checksum __dll31_flash_compute_checksum
#define osFlashInit __dll31_osFlashInit
#define flash_func_638 __dll31_flash_func_638
#define osFlashReadStatus __dll31_osFlashReadStatus
#define osFlashReadId __dll31_osFlashReadId
#define osFlashClearStatus __dll31_osFlashClearStatus
#define osFlashReadArray __dll31_osFlashReadArray
#define osFlashSectorErase __dll31_osFlashSectorErase
#define osFlashWriteBuffer __dll31_osFlashWriteBuffer
#define osFlashWriteArray __dll31_osFlashWriteArray
#define str7 __dll31_str7
#define str12 __dll31_str12
#define str4 __dll31_str4
#define flash_load_game __dll31_flash_load_game
#define str10 __dll31_str10
#define str14 __dll31_str14
#define str23 __dll31_str23
#define str3 __dll31_str3
#define str11 __dll31_str11
#define str8 __dll31_str8
#define flash_ctor __dll31_flash_ctor
#define str17 __dll31_str17
#define str16 __dll31_str16
#define str5 __dll31_str5
#define str18 __dll31_str18
#define str13 __dll31_str13
#define str22 __dll31_str22
#define flash_save_game __dll31_flash_save_game
#define str1 __dll31_str1
#define str19 __dll31_str19
#define str6 __dll31_str6
#define str9 __dll31_str9
#define str20 __dll31_str20
#define str2 __dll31_str2
#define flash_dtor __dll31_flash_dtor
#define str21 __dll31_str21
#define str15 __dll31_str15

#endif //_DLL_31_RECOMP_H
