// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_60_RECOMP_H
#define _DLL_60_RECOMP_H

#define dll_60_func_D0C __dll60_dll_60_func_D0C
#define dll_60_update1 __dll60_dll_60_update1
#define dll_60_dtor __dll60_dll_60_dtor
#define dll_60_ctor __dll60_dll_60_ctor
#define data_8 __dll60_data_8
#define dll_60_update2 __dll60_dll_60_update2
#define bss_0 __dll60_bss_0
#define dll_60_draw __dll60_dll_60_draw
#define bss_6 __dll60_bss_6
#define data_0 __dll60_data_0
#define bss_18 __dll60_bss_18
#define bss_14 __dll60_bss_14
#define bss_C __dll60_bss_C
#define bss_10 __dll60_bss_10
#define data_10 __dll60_data_10
#define bss_5 __dll60_bss_5
#define bss_8 __dll60_bss_8
#define data_4 __dll60_data_4
#define rodata_0 __dll60_rodata_0
#define data_18 __dll60_data_18
#define rodata_4 __dll60_rodata_4
#define bss_1C __dll60_bss_1C
#define bss_4 __dll60_bss_4
#define data_C __dll60_data_C

#endif //_DLL_60_RECOMP_H
