// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_61_RECOMP_H
#define _DLL_61_RECOMP_H

#define data_8 __dll61_data_8
#define bss_0 __dll61_bss_0
#define bss_2 __dll61_bss_2
#define data_0 __dll61_data_0
#define dll_61_update1 __dll61_dll_61_update1
#define bss_18 __dll61_bss_18
#define bss_14 __dll61_bss_14
#define dll_61_dtor __dll61_dll_61_dtor
#define bss_C __dll61_bss_C
#define bss_10 __dll61_bss_10
#define dll_61_draw __dll61_dll_61_draw
#define dll_61_ctor __dll61_dll_61_ctor
#define bss_8 __dll61_bss_8
#define data_4 __dll61_data_4
#define dll_61_update2 __dll61_dll_61_update2
#define bss_1 __dll61_bss_1
#define bss_4 __dll61_bss_4

#endif //_DLL_61_RECOMP_H
