// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_74_RECOMP_H
#define _DLL_74_RECOMP_H

#define str_1 __dll74_str_1
#define str_2 __dll74_str_2
#define str_3 __dll74_str_3
#define str_4 __dll74_str_4
#define str_5 __dll74_str_5
#define str_6 __dll74_str_6
#define sDefaultSounds __dll74_sDefaultSounds
#define sTextures __dll74_sTextures
#define sItems __dll74_sItems
#define sAllowButtons __dll74_sAllowButtons
#define sSelectedItem __dll74_sSelectedItem
#define sItemCount __dll74_sItemCount
#define sHighlightReverse __dll74_sHighlightReverse
#define sHighlightAlpha __dll74_sHighlightAlpha
#define sOpacity __dll74_sOpacity
#define sSounds __dll74_sSounds
#define sTextColorR __dll74_sTextColorR
#define sTextColorG __dll74_sTextColorG
#define sTextColorB __dll74_sTextColorB
#define sTextHighlightR __dll74_sTextHighlightR
#define sTextHighlightG __dll74_sTextHighlightG
#define sTextHighlightB __dll74_sTextHighlightB
#define picmenu_calculate_auto_width __dll74_picmenu_calculate_auto_width
#define picmenu_generate_item_background __dll74_picmenu_generate_item_background
#define picmenu_calculate_redraw_area __dll74_picmenu_calculate_redraw_area
#define picmenu_calculate_items_to_redraw __dll74_picmenu_calculate_items_to_redraw
#define picmenu_set_opacity __dll74_picmenu_set_opacity
#define picmenu_dtor __dll74_picmenu_dtor
#define picmenu_set_selected_item __dll74_picmenu_set_selected_item
#define picmenu_set_items __dll74_picmenu_set_items
#define picmenu_get_highlight_alpha __dll74_picmenu_get_highlight_alpha
#define picmenu_get_selected_item __dll74_picmenu_get_selected_item
#define picmenu_ctor __dll74_picmenu_ctor
#define picmenu_update_text __dll74_picmenu_update_text
#define picmenu_get_item_override __dll74_picmenu_get_item_override
#define picmenu_clear_items __dll74_picmenu_clear_items
#define picmenu_update __dll74_picmenu_update
#define picmenu_update_flags __dll74_picmenu_update_flags
#define picmenu_redraw_all __dll74_picmenu_redraw_all
#define picmenu_set_item_override __dll74_picmenu_set_item_override
#define picmenu_draw __dll74_picmenu_draw

#endif //_DLL_74_RECOMP_H
