// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_82_RECOMP_H
#define _DLL_82_RECOMP_H

#define func_18 __dll82_func_18
#define ctor __dll82_ctor
#define dtor __dll82_dtor

#endif //_DLL_82_RECOMP_H
