// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_83_RECOMP_H
#define _DLL_83_RECOMP_H

#define func_A4 __dll83_func_A4
#define func_18 __dll83_func_18
#define ctor __dll83_ctor
#define dtor __dll83_dtor

#endif //_DLL_83_RECOMP_H
