// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_94_RECOMP_H
#define _DLL_94_RECOMP_H

#define dll_94_func_7C __dll94_dll_94_func_7C
#define dll_94_func_18 __dll94_dll_94_func_18
#define dll_94_dtor __dll94_dll_94_dtor
#define dll_94_func_70 __dll94_dll_94_func_70
#define dll_94_ctor __dll94_dll_94_ctor
#define dll_94_func_64 __dll94_dll_94_func_64

#endif //_DLL_94_RECOMP_H
